/// Flutter icons TestIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TestIcon
///      fonts:
///       - asset: fonts/TestIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TestIcon {
  TestIcon._();

  static const _kFontFam = 'TestIcon';
  static const String? _kFontPkg = null;

  static const IconData logo_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
